# Generated by Django 6.0.3 on 2026-05-16 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('education', models.TextField()),
                ('projects', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='resumeversion',
            old_name='version_name',
            new_name='job_role',
        ),
        migrations.RemoveField(
            model_name='resumeversion',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile'),
        ),
    ]
